// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUecGLjU3HxX1v9ITI39y8zP_5rew1PRE',
    appId: '1:127019056763:web:93690acd3b046b39586cde',
    messagingSenderId: '127019056763',
    projectId: 'levelup-b8876',
    authDomain: 'levelup-b8876.firebaseapp.com',
    storageBucket: 'levelup-b8876.firebasestorage.app',
    measurementId: 'G-DZ7V0K6TK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB595I4mAm1ZawirsL2-CNEc15WZxGRmcA',
    appId: '1:127019056763:android:f66c44e11574213b586cde',
    messagingSenderId: '127019056763',
    projectId: 'levelup-b8876',
    storageBucket: 'levelup-b8876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzwjcdR75u05NCot6n43AhbbLSKAf816Y',
    appId: '1:127019056763:ios:98d076478f75b3e6586cde',
    messagingSenderId: '127019056763',
    projectId: 'levelup-b8876',
    storageBucket: 'levelup-b8876.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzwjcdR75u05NCot6n43AhbbLSKAf816Y',
    appId: '1:127019056763:ios:98d076478f75b3e6586cde',
    messagingSenderId: '127019056763',
    projectId: 'levelup-b8876',
    storageBucket: 'levelup-b8876.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUecGLjU3HxX1v9ITI39y8zP_5rew1PRE',
    appId: '1:127019056763:web:677371c73cb045c0586cde',
    messagingSenderId: '127019056763',
    projectId: 'levelup-b8876',
    authDomain: 'levelup-b8876.firebaseapp.com',
    storageBucket: 'levelup-b8876.firebasestorage.app',
    measurementId: 'G-DWNZP5VC3S',
  );
}
